### PR TITLE
Fix #39

### LINKED ISSUE #39: ^ versions handled incorrectly
A version in `Cargo.toml` like `^2` will match versions >=2 and <3. So it should show with a 👍 when the current version in crates.io is 2.5, but instead I get this:
```
pest = "^2.0"  Latest:2.1.0
pest_derive = "^2.0" Latest:2.1.0
```

However, cargo build is actually using 2.1.0.

### PR DESCRIPTION
**Pull request by RensAlthuis**
The issue for #39 was that there was no handling for caret requirements at all.
So I implemented a simple version of it. Someone should probably implement the other operators too. (which I might do at some point)

### CODE REVIEW

File: src/toml/decorations.ts [hunk 1]
```diff
@@ -22,6 +25,47 @@ export const latestVersion = (text: string) =>
     },
   });
 
+function parseSemVer(str : string): RegExpMatchArray {
```
Comment (serayuzgur) [inline src/toml/decorations.ts]: @RensAlthuis maybe you can use npm dependency semver, what do you think?

**Comment by RensAlthuis** [comment]
Ah yes, that is obviously a much better solution...
I changed it, this way it also checks for every other type of requirement.

**Comment by serayuzgur** [comment]
@RensAlthuis thanks for the fix. I will add your name to the readme and will publish these changes with the new version
